//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imppoa.HtmlZoning.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imppoa.HtmlZoning.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontStyle&lt;/Key&gt;
        ///    &lt;Value&gt;italic&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string ARTICLE {
            get {
                return ResourceManager.GetString("ARTICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string ASIDE {
            get {
                return ResourceManager.GetString("ASIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string AUDIO {
            get {
                return ResourceManager.GetString("AUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;18.73px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string BIG {
            get {
                return ResourceManager.GetString("BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginLeft&lt;/Key&gt;
        ///    &lt;Value&gt;40px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BLOCKQUOTE {
            get {
                return ResourceManager.GetString("BLOCKQUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;8px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginLeft&lt;/Key&gt;
        ///    &lt;Value&gt;8px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstrin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BODY {
            get {
                return ResourceManager.GetString("BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;backgroundColor&lt;/Key&gt;
        ///    &lt;Value&gt;rgb(240, 240, 240)&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomStyle&lt;/Key&gt;
        ///    &lt;Value&gt;outset&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomWidth&lt;/Key&gt;
        ///    &lt;Value&gt;3p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BUTTON {
            get {
                return ResourceManager.GetString("BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-caption&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;textAlign&lt;/Key&gt;
        ///    &lt;Value&gt;center&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string CAPTION {
            get {
                return ResourceManager.GetString("CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;textAlign&lt;/Key&gt;
        ///    &lt;Value&gt;center&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string CENTER {
            get {
                return ResourceManager.GetString("CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontStyle&lt;/Key&gt;
        ///    &lt;Value&gt;italic&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string CITE {
            get {
                return ResourceManager.GetString("CITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontFamily&lt;/Key&gt;
        ///    &lt;Value&gt;Courier New&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.33px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string CODE {
            get {
                return ResourceManager.GetString("CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-column&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string COL {
            get {
                return ResourceManager.GetString("COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-column-group&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string COLGROUP {
            get {
                return ResourceManager.GetString("COLGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string DATALIST {
            get {
                return ResourceManager.GetString("DATALIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginLeft&lt;/Key&gt;
        ///    &lt;Value&gt;40px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string DD {
            get {
                return ResourceManager.GetString("DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;textDecoration&lt;/Key&gt;
        ///    &lt;Value&gt;line-through&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string DEL {
            get {
                return ResourceManager.GetString("DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontStyle&lt;/Key&gt;
        ///    &lt;Value&gt;italic&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string DFN {
            get {
                return ResourceManager.GetString("DFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginTop&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DIR {
            get {
                return ResourceManager.GetString("DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string DIV {
            get {
                return ResourceManager.GetString("DIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginTop&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DL {
            get {
                return ResourceManager.GetString("DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string DT {
            get {
                return ResourceManager.GetString("DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontStyle&lt;/Key&gt;
        ///    &lt;Value&gt;italic&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string EM {
            get {
                return ResourceManager.GetString("EM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomStyle&lt;/Key&gt;
        ///    &lt;Value&gt;groove&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomWidth&lt;/Key&gt;
        ///    &lt;Value&gt;2px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderLeftStyle&lt;/Key&gt;
        ///    &lt;Value&gt;groove&lt;/Value&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FIELDSET {
            get {
                return ResourceManager.GetString("FIELDSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string FIGCAPTION {
            get {
                return ResourceManager.GetString("FIGCAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginLeft&lt;/Key&gt;
        ///    &lt;Value&gt;40px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FIGURE {
            get {
                return ResourceManager.GetString("FIGURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string FOOTER {
            get {
                return ResourceManager.GetString("FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string FORM {
            get {
                return ResourceManager.GetString("FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string FRAME {
            get {
                return ResourceManager.GetString("FRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string FRAMESET {
            get {
                return ResourceManager.GetString("FRAMESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;32px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string H1 {
            get {
                return ResourceManager.GetString("H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;24px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string H2 {
            get {
                return ResourceManager.GetString("H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;18.73px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstrin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string H3 {
            get {
                return ResourceManager.GetString("H3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;21.28px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstrings [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string H4 {
            get {
                return ResourceManager.GetString("H4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.26px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstrin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string H5 {
            get {
                return ResourceManager.GetString("H5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;10.73px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstrin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string H6 {
            get {
                return ResourceManager.GetString("H6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string HEAD {
            get {
                return ResourceManager.GetString("HEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string HGROUP {
            get {
                return ResourceManager.GetString("HGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomStyle&lt;/Key&gt;
        ///    &lt;Value&gt;inset&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomWidth&lt;/Key&gt;
        ///    &lt;Value&gt;1px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderLeftStyle&lt;/Key&gt;
        ///    &lt;Value&gt;inset&lt;/Value&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontStyle&lt;/Key&gt;
        ///    &lt;Value&gt;italic&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomStyle&lt;/Key&gt;
        ///    &lt;Value&gt;inset&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomWidth&lt;/Key&gt;
        ///    &lt;Value&gt;2px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderLeftStyle&lt;/Key&gt;
        ///    &lt;Value&gt;inset&lt;/Value&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IFRAME {
            get {
                return ResourceManager.GetString("IFRAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;backgroundColor&lt;/Key&gt;
        ///    &lt;Value&gt;rgb(255, 255, 255)&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomStyle&lt;/Key&gt;
        ///    &lt;Value&gt;inset&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomWidth&lt;/Key&gt;
        ///    &lt;Value&gt;2px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INPUT {
            get {
                return ResourceManager.GetString("INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;textDecoration&lt;/Key&gt;
        ///    &lt;Value&gt;underline&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string INS {
            get {
                return ResourceManager.GetString("INS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontFamily&lt;/Key&gt;
        ///    &lt;Value&gt;Courier New&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.33px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string KBD {
            get {
                return ResourceManager.GetString("KBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;paddingLeft&lt;/Key&gt;
        ///    &lt;Value&gt;2px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;paddingRight&lt;/Key&gt;
        ///    &lt;Value&gt;2px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string LEGEND {
            get {
                return ResourceManager.GetString("LEGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;list-item&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;listStylePosition&lt;/Key&gt;
        ///    &lt;Value&gt;inside&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontFamily&lt;/Key&gt;
        ///    &lt;Value&gt;Courier New&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;10.06px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LISTING {
            get {
                return ResourceManager.GetString("LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;backgroundColor&lt;/Key&gt;
        ///    &lt;Value&gt;rgb(255, 255, 0)&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string MARK {
            get {
                return ResourceManager.GetString("MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string MARQUEE {
            get {
                return ResourceManager.GetString("MARQUEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginTop&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string META {
            get {
                return ResourceManager.GetString("META", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string NAV {
            get {
                return ResourceManager.GetString("NAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string NOEMBED {
            get {
                return ResourceManager.GetString("NOEMBED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string NOFRAMES {
            get {
                return ResourceManager.GetString("NOFRAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string NOSCRIPT {
            get {
                return ResourceManager.GetString("NOSCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;listStyleType&lt;/Key&gt;
        ///    &lt;Value&gt;decimal&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OL {
            get {
                return ResourceManager.GetString("OL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;600&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string OPTGROUP {
            get {
                return ResourceManager.GetString("OPTGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginTop&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontFamily&lt;/Key&gt;
        ///    &lt;Value&gt;Courier New&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.33px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PLAINTEXT {
            get {
                return ResourceManager.GetString("PLAINTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontFamily&lt;/Key&gt;
        ///    &lt;Value&gt;Courier New&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.33px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PRE {
            get {
                return ResourceManager.GetString("PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomColor&lt;/Key&gt;
        ///    &lt;Value&gt;transparent&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomStyle&lt;/Key&gt;
        ///    &lt;Value&gt;solid&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomWidth&lt;/Key&gt;
        ///    &lt;Value&gt;1px&lt;/Val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PROGRESS {
            get {
                return ResourceManager.GetString("PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;ruby-text&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string RT {
            get {
                return ResourceManager.GetString("RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;ruby&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string RUBY {
            get {
                return ResourceManager.GetString("RUBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;textDecoration&lt;/Key&gt;
        ///    &lt;Value&gt;line-through&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontFamily&lt;/Key&gt;
        ///    &lt;Value&gt;Courier New&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.33px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string SAMP {
            get {
                return ResourceManager.GetString("SAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string SCRIPT {
            get {
                return ResourceManager.GetString("SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string SECTION {
            get {
                return ResourceManager.GetString("SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;backgroundColor&lt;/Key&gt;
        ///    &lt;Value&gt;rgb(255, 255, 255)&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomColor&lt;/Key&gt;
        ///    &lt;Value&gt;rgb(227, 227, 227)&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomStyle&lt;/Key&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.26px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string SMALL {
            get {
                return ResourceManager.GetString("SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;backgroundColor&lt;/Key&gt;
        ///    &lt;Value&gt;transparent&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;backgroundImage&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;baselineShift&lt;/Key&gt;
        ///    &lt;Value&gt;baseline&lt;/Value&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SPAN {
            get {
                return ResourceManager.GetString("SPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;textDecoration&lt;/Key&gt;
        ///    &lt;Value&gt;line-through&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string STRIKE {
            get {
                return ResourceManager.GetString("STRIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string STRONG {
            get {
                return ResourceManager.GetString("STRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string STYLE {
            get {
                return ResourceManager.GetString("STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;11.06px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string SUB {
            get {
                return ResourceManager.GetString("SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;11.06px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string SUP {
            get {
                return ResourceManager.GetString("SUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderSpacing&lt;/Key&gt;
        ///    &lt;Value&gt;2px 2px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;boxSizing&lt;/Key&gt;
        ///    &lt;Value&gt;border-box&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table&lt;/Value&gt;
        ///  &lt;/KeyValueOf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TABLE {
            get {
                return ResourceManager.GetString("TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-row-group&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;verticalAlign&lt;/Key&gt;
        ///    &lt;Value&gt;middle&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string TBODY {
            get {
                return ResourceManager.GetString("TBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-cell&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;paddingBottom&lt;/Key&gt;
        ///    &lt;Value&gt;1px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;paddingLeft&lt;/Key&gt;
        ///    &lt;Value&gt;1px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;backgroundColor&lt;/Key&gt;
        ///    &lt;Value&gt;rgb(255, 255, 255)&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomStyle&lt;/Key&gt;
        ///    &lt;Value&gt;inset&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;borderBottomWidth&lt;/Key&gt;
        ///    &lt;Value&gt;2px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TEXTAREA {
            get {
                return ResourceManager.GetString("TEXTAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-footer-group&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;verticalAlign&lt;/Key&gt;
        ///    &lt;Value&gt;middle&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string TFOOT {
            get {
                return ResourceManager.GetString("TFOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-cell&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontWeight&lt;/Key&gt;
        ///    &lt;Value&gt;700&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;paddingBottom&lt;/Key&gt;
        ///    &lt;Value&gt;1px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstrin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-header-group&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;verticalAlign&lt;/Key&gt;
        ///    &lt;Value&gt;middle&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string THEAD {
            get {
                return ResourceManager.GetString("THEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;none&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;table-row&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontFamily&lt;/Key&gt;
        ///    &lt;Value&gt;Courier New&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.33px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;textDecoration&lt;/Key&gt;
        ///    &lt;Value&gt;underline&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginBottom&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;marginTop&lt;/Key&gt;
        ///    &lt;Value&gt;16px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UL {
            get {
                return ResourceManager.GetString("UL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontStyle&lt;/Key&gt;
        ///    &lt;Value&gt;italic&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///&lt;/ArrayOfKeyValueOfstringstring&gt;.
        /// </summary>
        internal static string VAR {
            get {
                return ResourceManager.GetString("VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfKeyValueOfstringstring xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;display&lt;/Key&gt;
        ///    &lt;Value&gt;block&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontFamily&lt;/Key&gt;
        ///    &lt;Value&gt;Courier New&lt;/Value&gt;
        ///  &lt;/KeyValueOfstringstring&gt;
        ///  &lt;KeyValueOfstringstring&gt;
        ///    &lt;Key&gt;fontSize&lt;/Key&gt;
        ///    &lt;Value&gt;13.33px&lt;/Value&gt;
        ///  &lt;/KeyValueOfstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMP {
            get {
                return ResourceManager.GetString("XMP", resourceCulture);
            }
        }
    }
}
